[package]
name = "wordle"
version = "0.1.0"
edition = "2021"
authors = ["Zane Duffield"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
rayon = "1.5.1"
rand = "0.8.4"
itertools = "0.10.3"
pancurses = "0.17.0"
